api_platform:
  title: Smart Choice
  version: 0.0.0
  mapping:
    paths: ['%kernel.project_dir%/src/Entity']
  patch_formats:
    json:
      - application/merge-patch+json
      - application/json
  swagger:
    versions: [3]

  formats:
    jsonld:  ['application/ld+json']
    jsonhal: ['application/hal+json']
    jsonapi: ['application/vnd.api+json']
    json:    ['application/json']
    xml:     ['application/xml', 'text/xml']
    yaml:    ['application/x-yaml']
    csv:     ['text/csv']
    html:    ['text/html']

  exception_to_status:
    # The 4 following handlers are registered by default, keep those lines to prevent unexpected side effects
    Symfony\Component\Serializer\Exception\ExceptionInterface: 400 # Use a raw status code (recommended)
    ApiPlatform\Core\Exception\InvalidArgumentException: !php/const Symfony\Component\HttpFoundation\Response::HTTP_BAD_REQUEST
    ApiPlatform\Core\Exception\FilterValidationException: 400
    Doctrine\ORM\OptimisticLockException: 409

    # Custom mapping
    Symfony\Component\Security\Core\Exception\AuthenticationException: 401
    Symfony\Component\Security\Core\Exception\AccessDeniedException: 403
