name: Api checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Get Composer Cache Directory
      id: composer-cache
      run: |
        echo "::set-output name=dir::$(composer config cache-files-dir -d api)"

    - name: Cache Composer Downloads
      uses: actions/cache@v1
      with:
        path: ${{ steps.composer-cache.outputs.dir }}
        key: ${{ runner.os }}-composer-${{ hashFiles('**/api/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-composer-
      
    - name: Cache PHP dependencies
      uses: actions/cache@v1
      with:
        path: api/vendor
        key: ${{ runner.OS }}-build-${{ hashFiles('**/api/composer.lock') }}

    - name: Init composer
      uses: php-actions/composer@v1
      with:
        command: install -d api

    - name: Check code style
      uses: php-actions/composer@v1
      with:
        command: run style:check -d api
