name: Docker Image CI

on:
  push:
    branches:
      - master
      - feature/workflows

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the php image
      run: docker build ./api --tag smart-choice/php:master --target php
    - name: Build the nginx image
      run: docker build ./api --tag smart-choice/nginx:master --target nginx
