name: Api checks

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the php image
      run: docker build ./api --tag smart-choice/php:master --target php --build-arg "APP_ENV=dev"
    - name: Check code style
      run: docker run --rm smart-choice/php:master sh -c 'composer install && composer run style:check'
